output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value       = "${module.eks.kubeconfig}"
}

output "config_map_aws_auth" {
  description = "config map auth for workers to join cluster"
  value       = "${module.eks.config_map_aws_auth}"
}
